#!/bin/sh

CRYPTOREST__COMMON_WWW_DIR="$CRYPTOREST_WWW_DIR/_common"
CRYPTOREST__COMMON_WWW_HTML_DIR="$CRYPTOREST__COMMON_WWW_DIR/html"
CRYPTOREST__COMMON_WWW_HTML_ERRORS_DIR="$CRYPTOREST__COMMON_WWW_HTML_DIR/errors"
CRYPTOREST__COMMON_WWW_ASSETS_DIR="$CRYPTOREST__COMMON_WWW_DIR/assets"
CRYPTOREST__COMMON_WWW_ASSETS_ICONS_DIR="$CRYPTOREST__COMMON_WWW_ASSETS_DIR/icons"
CRYPTOREST__COMMON_TITLE='CryptoREST Common'


cryptorest_common_prepare()
{
    if [ -d "$CRYPTOREST__COMMON_WWW_DIR" ]; then
        chmod 700 "$CRYPTOREST__COMMON_WWW_DIR"
    fi
    if [ -d "$CRYPTOREST__COMMON_WWW_HTML_DIR" ]; then
        chmod 700 "$CRYPTOREST__COMMON_WWW_HTML_DIR"
    fi
    if [ -d "$CRYPTOREST__COMMON_WWW_HTML_ERRORS_DIR" ]; then
        chmod 700 "$CRYPTOREST__COMMON_WWW_HTML_ERRORS_DIR"
    fi
    if [ -d "$CRYPTOREST__COMMON_WWW_ASSETS_DIR" ]; then
        chmod 700 "$CRYPTOREST__COMMON_WWW_ASSETS_DIR"
    fi

    rm -rf "$CRYPTOREST__COMMON_WWW_DIR"
}

cryptorest_common_install()
{
    mkdir -p "$CRYPTOREST__COMMON_WWW_HTML_DIR" && \
    chmod 700 "$CRYPTOREST__COMMON_WWW_HTML_DIR"

}

cryptorest_common_define()
{
    cp -r "$CRYPTOREST_CURRENT_DIR/_common/www/"* "$CRYPTOREST__COMMON_WWW_DIR/" && \
    chmod 400 "$CRYPTOREST__COMMON_WWW_DIR/"* && \
    chmod 700 "$CRYPTOREST__COMMON_WWW_HTML_DIR" && \
    chmod 444 "$CRYPTOREST__COMMON_WWW_HTML_DIR/"*.html && \
    chmod 700 "$CRYPTOREST__COMMON_WWW_HTML_ERRORS_DIR" && \
    chmod 444 "$CRYPTOREST__COMMON_WWW_HTML_ERRORS_DIR/"*.html && \
    chmod 555 "$CRYPTOREST__COMMON_WWW_HTML_ERRORS_DIR" && \
    chmod 555 "$CRYPTOREST__COMMON_WWW_HTML_DIR" && \
    chmod 700 "$CRYPTOREST__COMMON_WWW_ASSETS_DIR" && \
    chmod 700 "$CRYPTOREST__COMMON_WWW_ASSETS_ICONS_DIR" && \
    chmod 444 "$CRYPTOREST__COMMON_WWW_ASSETS_ICONS_DIR/"* && \
    chmod 555 "$CRYPTOREST__COMMON_WWW_ASSETS_ICONS_DIR" && \
    chmod 555 "$CRYPTOREST__COMMON_WWW_ASSETS_DIR" && \
    chmod 555 "$CRYPTOREST__COMMON_WWW_DIR" && \

    echo "$CRYPTOREST__COMMON_TITLE: init"
    echo ''
}


cryptorest_common_prepare && \
cryptorest_common_install && \
cryptorest_common_define
